source "https://rubygems.org"

ruby File.read("#{__dir__}/../.ruby-version").strip

gem "jekyll", "~> 4.3"

group :jekyll_plugins do
  gem "jekyll-bookshop", "~> 3.9"
  gem "jekyll-watch", :git => "https://github.com/CloudCannon/jekyll-watch"
  gem "jekyll-postcss-v2"
  gem "jekyll-archives", "~> 2.2.1"
  gem "jekyll-feed", "~> 0.15.1"
  gem "jekyll-redirect-from"
  gem "jekyll-sitemap"
end

gem "webrick"