website_theme: Hydra
website_name: Causey
live_domain_url: https://www.causey.app
website_description_text: Strategic Planning Software for mission-driven organizations.
social_media_share_image:
twitter_handle: '@causeystrat'
icons:
  small_bookmark_icon_image: /images/icons/favicon-16.jpg
  large_bookmark_icon_image: /images/icons/favicon-32.jpg
  small_mobile_icon_image: /images/icons/mobile-128.jpg
  large_mobile_icon_image: /images/icons/mobile-256.jpg
