website_theme: Hydra
website_name: Causey
live_domain_url: https://www.causey.app
website_description_text: Strategic Planning Software for mission-driven organizations.
social_media_share_image: /uploads/causey_notagling-share.png
twitter_handle: '@causeystrat'
