website_theme: Hydra
website_name: Causey
live_domain_url: https://www.causey.app
website_description_text: Strategic planning software built for nonprofits. Get your plan off the shelf, align your team, and show your board real progress.
social_media_share_image: /uploads/causey_notagling-share.png
twitter_handle: '@causeystrat'
